services:
  vitepress:
    container_name: vitepress
    restart: always
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
    - .env
    ports:
    - 3001:5173
    attach: true
