services:
  vitepress:
    container_name: vitepress
    restart: always
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile.vitepress
      target: dev
    # image: mirai/front:dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
    - .env
    ports:
    - 5173:5173
    attach: true