services:
  vitepress:
    container_name: vitepress
    platform: linux/amd64
    restart: always
    # working_dir: /app
    build:
      context:  apps/client
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./apps/client:/app
      - /app/node_modules
    env_file:
    - .env
    ports:
    - 3001:5173
    # attach: true

  api:
    container_name: translator
    platform: linux/amd64
    env_file:
      - .env
    build:
      context: apps/server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./apps/server/app:/app/app
    restart: always