services:
  vitepress:
    container_name: vitepress
    restart: always
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
    - .env
    ports:
    - 5173:5173
    attach: true

  # translator:
  #   container_name: translator-py
  #   restart: always
  #   working_dir: /app
  #   build:
  #     context: ./scripts/translate-py
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./scripts/translate-py:/app
  #     - ./scripts/translate-py/.venv:/app/.venv
  #   attach: true