[project]
name = "doc-translator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "httpx>=0.28.1",
    "marked>=0.9.1",
    "ollama>=0.4.8",
    "requests>=2.32.3",
]
